/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as UserIdIndexImport } from './routes/$userId/index'
import { Route as UserIdEditPoliciesIndexImport } from './routes/$userId/edit-policies/index'
import { Route as UserIdEditPoliciesEditBeneficiariesIndexImport } from './routes/$userId/edit-policies/edit-beneficiaries/index'
import { Route as UserIdEditPoliciesEditBeneficiariesLayoutImport } from './routes/$userId/edit-policies/edit-beneficiaries/_layout'
import { Route as UserIdEditPoliciesEditBeneficiariesPolicynumberIndexImport } from './routes/$userId/edit-policies/edit-beneficiaries/$policy_number/index'
import { Route as UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexImport } from './routes/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/index'
import { Route as UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitImport } from './routes/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
import { Route as UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryImport } from './routes/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary'
import { Route as UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsImport } from './routes/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'

// Create Virtual Routes

const UserIdEditPoliciesEditBeneficiariesImport = createFileRoute(
  '/$userId/edit-policies/edit-beneficiaries',
)()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdIndexRoute = UserIdIndexImport.update({
  id: '/$userId/',
  path: '/$userId/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdEditPoliciesEditBeneficiariesRoute =
  UserIdEditPoliciesEditBeneficiariesImport.update({
    id: '/$userId/edit-policies/edit-beneficiaries',
    path: '/$userId/edit-policies/edit-beneficiaries',
    getParentRoute: () => rootRoute,
  } as any)

const UserIdEditPoliciesIndexRoute = UserIdEditPoliciesIndexImport.update({
  id: '/$userId/edit-policies/',
  path: '/$userId/edit-policies/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdEditPoliciesEditBeneficiariesIndexRoute =
  UserIdEditPoliciesEditBeneficiariesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
  } as any)

const UserIdEditPoliciesEditBeneficiariesLayoutRoute =
  UserIdEditPoliciesEditBeneficiariesLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
  } as any)

const UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute =
  UserIdEditPoliciesEditBeneficiariesPolicynumberIndexImport.update({
    id: '/$policy_number/',
    path: '/$policy_number/',
    getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
  } as any)

const UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute =
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexImport.update(
    {
      id: '/$policy_number/modify_policy/',
      path: '/$policy_number/modify_policy/',
      getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
    } as any,
  )

const UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute =
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitImport.update(
    {
      id: '/$policy_number/modify_policy/verify-and-submit',
      path: '/$policy_number/modify_policy/verify-and-submit',
      getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
    } as any,
  )

const UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute =
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryImport.update(
    {
      id: '/$policy_number/modify_policy/edit-beneficiary',
      path: '/$policy_number/modify_policy/edit-beneficiary',
      getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
    } as any,
  )

const UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute =
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsImport.update(
    {
      id: '/$policy_number/modify_policy/allocations',
      path: '/$policy_number/modify_policy/allocations',
      getParentRoute: () => UserIdEditPoliciesEditBeneficiariesRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/$userId/': {
      id: '/$userId/'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof UserIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/$userId/edit-policies/': {
      id: '/$userId/edit-policies/'
      path: '/$userId/edit-policies'
      fullPath: '/$userId/edit-policies'
      preLoaderRoute: typeof UserIdEditPoliciesIndexImport
      parentRoute: typeof rootRoute
    }
    '/$userId/edit-policies/edit-beneficiaries': {
      id: '/$userId/edit-policies/edit-beneficiaries'
      path: '/$userId/edit-policies/edit-beneficiaries'
      fullPath: '/$userId/edit-policies/edit-beneficiaries'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
      parentRoute: typeof rootRoute
    }
    '/$userId/edit-policies/edit-beneficiaries/_layout': {
      id: '/$userId/edit-policies/edit-beneficiaries/_layout'
      path: '/$userId/edit-policies/edit-beneficiaries'
      fullPath: '/$userId/edit-policies/edit-beneficiaries'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesLayoutImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesRoute
    }
    '/$userId/edit-policies/edit-beneficiaries/': {
      id: '/$userId/edit-policies/edit-beneficiaries/'
      path: '/'
      fullPath: '/$userId/edit-policies/edit-beneficiaries/'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesIndexImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
    }
    '/$userId/edit-policies/edit-beneficiaries/$policy_number/': {
      id: '/$userId/edit-policies/edit-beneficiaries/$policy_number/'
      path: '/$policy_number'
      fullPath: '/$userId/edit-policies/edit-beneficiaries/$policy_number'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberIndexImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
    }
    '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': {
      id: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
      path: '/$policy_number/modify_policy/allocations'
      fullPath: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
    }
    '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary': {
      id: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary'
      path: '/$policy_number/modify_policy/edit-beneficiary'
      fullPath: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
    }
    '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': {
      id: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
      path: '/$policy_number/modify_policy/verify-and-submit'
      fullPath: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
    }
    '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/': {
      id: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/'
      path: '/$policy_number/modify_policy'
      fullPath: '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy'
      preLoaderRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexImport
      parentRoute: typeof UserIdEditPoliciesEditBeneficiariesImport
    }
  }
}

// Create and export the route tree

interface UserIdEditPoliciesEditBeneficiariesRouteChildren {
  UserIdEditPoliciesEditBeneficiariesLayoutRoute: typeof UserIdEditPoliciesEditBeneficiariesLayoutRoute
  UserIdEditPoliciesEditBeneficiariesIndexRoute: typeof UserIdEditPoliciesEditBeneficiariesIndexRoute
  UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute: typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

const UserIdEditPoliciesEditBeneficiariesRouteChildren: UserIdEditPoliciesEditBeneficiariesRouteChildren =
  {
    UserIdEditPoliciesEditBeneficiariesLayoutRoute:
      UserIdEditPoliciesEditBeneficiariesLayoutRoute,
    UserIdEditPoliciesEditBeneficiariesIndexRoute:
      UserIdEditPoliciesEditBeneficiariesIndexRoute,
    UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute:
      UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute,
    UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute:
      UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute,
    UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute:
      UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute,
    UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute:
      UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute,
    UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute:
      UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute,
  }

const UserIdEditPoliciesEditBeneficiariesRouteWithChildren =
  UserIdEditPoliciesEditBeneficiariesRoute._addFileChildren(
    UserIdEditPoliciesEditBeneficiariesRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$userId': typeof UserIdIndexRoute
  '/$userId/edit-policies': typeof UserIdEditPoliciesIndexRoute
  '/$userId/edit-policies/edit-beneficiaries': typeof UserIdEditPoliciesEditBeneficiariesLayoutRoute
  '/$userId/edit-policies/edit-beneficiaries/': typeof UserIdEditPoliciesEditBeneficiariesIndexRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$userId': typeof UserIdIndexRoute
  '/$userId/edit-policies': typeof UserIdEditPoliciesIndexRoute
  '/$userId/edit-policies/edit-beneficiaries': typeof UserIdEditPoliciesEditBeneficiariesIndexRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$userId/': typeof UserIdIndexRoute
  '/$userId/edit-policies/': typeof UserIdEditPoliciesIndexRoute
  '/$userId/edit-policies/edit-beneficiaries': typeof UserIdEditPoliciesEditBeneficiariesRouteWithChildren
  '/$userId/edit-policies/edit-beneficiaries/_layout': typeof UserIdEditPoliciesEditBeneficiariesLayoutRoute
  '/$userId/edit-policies/edit-beneficiaries/': typeof UserIdEditPoliciesEditBeneficiariesIndexRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberIndexRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyAllocationsRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyEditBeneficiaryRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyVerifyAndSubmitRoute
  '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/': typeof UserIdEditPoliciesEditBeneficiariesPolicynumberModifypolicyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/$userId'
    | '/$userId/edit-policies'
    | '/$userId/edit-policies/edit-beneficiaries'
    | '/$userId/edit-policies/edit-beneficiaries/'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/$userId'
    | '/$userId/edit-policies'
    | '/$userId/edit-policies/edit-beneficiaries'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/$userId/'
    | '/$userId/edit-policies/'
    | '/$userId/edit-policies/edit-beneficiaries'
    | '/$userId/edit-policies/edit-beneficiaries/_layout'
    | '/$userId/edit-policies/edit-beneficiaries/'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit'
    | '/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  UserIdEditPoliciesIndexRoute: typeof UserIdEditPoliciesIndexRoute
  UserIdEditPoliciesEditBeneficiariesRoute: typeof UserIdEditPoliciesEditBeneficiariesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  UserIdEditPoliciesIndexRoute: UserIdEditPoliciesIndexRoute,
  UserIdEditPoliciesEditBeneficiariesRoute:
    UserIdEditPoliciesEditBeneficiariesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/$userId/",
        "/$userId/edit-policies/",
        "/$userId/edit-policies/edit-beneficiaries"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/$userId/": {
      "filePath": "$userId/index.tsx"
    },
    "/$userId/edit-policies/": {
      "filePath": "$userId/edit-policies/index.tsx"
    },
    "/$userId/edit-policies/edit-beneficiaries": {
      "filePath": "$userId/edit-policies/edit-beneficiaries",
      "children": [
        "/$userId/edit-policies/edit-beneficiaries/_layout",
        "/$userId/edit-policies/edit-beneficiaries/",
        "/$userId/edit-policies/edit-beneficiaries/$policy_number/",
        "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations",
        "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary",
        "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit",
        "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/"
      ]
    },
    "/$userId/edit-policies/edit-beneficiaries/_layout": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/_layout.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    },
    "/$userId/edit-policies/edit-beneficiaries/": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/index.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    },
    "/$userId/edit-policies/edit-beneficiaries/$policy_number/": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/$policy_number/index.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    },
    "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/allocations.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    },
    "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/edit-beneficiary.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    },
    "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/verify-and-submit.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    },
    "/$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/": {
      "filePath": "$userId/edit-policies/edit-beneficiaries/$policy_number/modify_policy/index.tsx",
      "parent": "/$userId/edit-policies/edit-beneficiaries"
    }
  }
}
ROUTE_MANIFEST_END */
